package metier;

// Generated 3 juin 2015 10:21:18 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "action", catalog = "permispiste")
public class Action implements java.io.Serializable {

	private int numaction;
	private Action action;
	private String libaction;
	private Integer scoremin;
	
	private List<Indicateur> mesIndicateurs = new ArrayList<Indicateur>();
	
	
	private List<Jeu> mesJeux = new ArrayList<Jeu>();
	
	private List<Action> mesActions = new ArrayList<Action>();
;
	private List<Objectif> mesObjectifs = new ArrayList<Objectif>();

	private List<Obtient> mesResultats = new ArrayList<Obtient>();
	
	private List<Regle> mesRegles = new ArrayList<Regle>();
	
	public Action() {
	}

	public Action(int numaction) {
		this.numaction = numaction;
	}

	public Action(int numaction, Action action, String libaction,
			Integer scoremin, List<Indicateur>  indicateurs, List<Jeu> jeux, List<Action> actions,
			List<Objectif> objectifs, List<Obtient> obtients, List<Regle> regles) {
		this.numaction = numaction;
		this.action = action;
		this.libaction = libaction;
		this.scoremin = scoremin;
		this.mesIndicateurs = indicateurs;
		this.mesJeux = jeux;
		this.mesActions = actions;
		this.mesObjectifs = objectifs;
		this.mesResultats = obtients;
		this.mesRegles = regles;
	}

	@Id
	@Column(name = "NUMACTION", unique = true, nullable = false)
	public int getNumaction() {
		return this.numaction;
	}

	public void setNumaction(int numaction) {
		this.numaction = numaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACT_NUMACTION")
	public Action getAction() {
		return this.action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

	@Column(name = "LIBACTION", length = 25)
	public String getLibaction() {
		return this.libaction;
	}

	public void setLibaction(String libaction) {
		this.libaction = libaction;
	}

	@Column(name = "SCOREMIN")
	public Integer getScoremin() {
		return this.scoremin;
	}

	public void setScoremin(Integer scoremin) {
		this.scoremin = scoremin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "action")
	public List<Indicateur> getIndicateurs() {
		return this.mesIndicateurs;
	}

	public void setIndicateurs(List<Indicateur> indicateurs) {
		this.mesIndicateurs = indicateurs;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "actions")
	public List<Jeu> getJeus() {
		return this.mesJeux;
	}

	public void setJeus(List<Jeu> jeux) {
		this.mesJeux = jeux;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "action")
	public List<Action> getActions() {
		return this.mesActions;
	}

	public void setActions(List<Action> actions) {
		this.mesActions = actions;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "est_associe", catalog = "permispiste", joinColumns = { @JoinColumn(name = "NUMACTION", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "NUMOBJECTIF", nullable = false, updatable = false) })
	public List<Objectif> getObjectifs() {
		return this.mesObjectifs;
	}

	public void setObjectifs(List<Objectif> objectifs) {
		this.mesObjectifs = objectifs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "action")
	public List<Obtient> getObtients() {
		return this.mesResultats;
	}

	public void setObtients(List<Obtient> obtients) {
		this.mesResultats = obtients;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "possede", catalog = "permispiste", joinColumns = { @JoinColumn(name = "NUMACTION", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "NUMREGLE", nullable = false, updatable = false) })
	public List<Regle> getRegles() {
		return this.mesRegles;
	}

	public void setRegles(List<Regle> regles) {
		this.mesRegles = regles;
	}

}
