package metier;

// Generated 3 juin 2015 10:21:18 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Indicateur generated by hbm2java
 */
@Entity
@Table(name = "indicateur", catalog = "permispiste")
public class Indicateur implements java.io.Serializable {

	private int numindic;
	private Action action;
	private String libindic;
	private Integer poids;

	public Indicateur() {
	}

	public Indicateur(int numindic, Action action) {
		this.numindic = numindic;
		this.action = action;
	}

	public Indicateur(int numindic, Action action, String libindic,
			Integer poids) {
		this.numindic = numindic;
		this.action = action;
		this.libindic = libindic;
		this.poids = poids;
	}

	@Id
	@Column(name = "NUMINDIC", unique = true, nullable = false)
	public int getNumindic() {
		return this.numindic;
	}

	public void setNumindic(int numindic) {
		this.numindic = numindic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUMACTION", nullable = false)
	public Action getAction() {
		return this.action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

	@Column(name = "LIBINDIC", length = 20)
	public String getLibindic() {
		return this.libindic;
	}

	public void setLibindic(String libindic) {
		this.libindic = libindic;
	}

	@Column(name = "POIDS")
	public Integer getPoids() {
		return this.poids;
	}

	public void setPoids(Integer poids) {
		this.poids = poids;
	}

}
