package metier;

// Generated 3 juin 2015 10:21:18 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Objectif generated by hbm2java
 */
@Entity
@Table(name = "objectif", catalog = "permispiste")
public class Objectif implements java.io.Serializable {

	private int numobjectif;
	private String libobectif;
	private List<Action> mesActions = new ArrayList<Action>();
	private List<Mission> mesMissions = new ArrayList<Mission>();
	

	public Objectif() {
	}

	public Objectif(int numobjectif) {
		this.numobjectif = numobjectif;
	}

	public Objectif(int numobjectif, String libobectif, List<Action> mesA,
			List<Mission> missions) {
		this.numobjectif = numobjectif;
		this.libobectif = libobectif;
		this.mesActions = mesA;
		this.mesMissions = missions;
	}

	@Id
	@Column(name = "NUMOBJECTIF", unique = true, nullable = false)
	public int getNumobjectif() {
		return this.numobjectif;
	}

	public void setNumobjectif(int numobjectif) {
		this.numobjectif = numobjectif;
	}

	@Column(name = "LIBOBECTIF", length = 25)
	public String getLibobectif() {
		return this.libobectif;
	}

	public void setLibobectif(String libobectif) {
		this.libobectif = libobectif;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "objectifs")
	public List<Action> getActions() {
		return this.mesActions;
	}

	public void setActions(List<Action> actions) {
		this.mesActions = actions;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "objectifs")
	public List<Mission> getMissions() {
		return this.mesMissions;
	}

	public void setMissions(List<Mission> missions) {
		this.mesMissions = missions;
	}

}
