package metier;

// Generated 3 juin 2015 10:21:18 by Hibernate Tools 4.3.1

import java.util.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Regle generated by hbm2java
 */
@Entity
@Table(name = "regle", catalog = "permispiste")
public class Regle implements java.io.Serializable {

	private int numregle;
	private String libregle;
	private Integer scoremin;
	private List<Action> mesActions = new ArrayList<Action>();

	public Regle() {
	}

	public Regle(int numregle) {
		this.numregle = numregle;
	}

	public Regle(int numregle, String libregle, Integer scoremin, List<Action>  actions) {
		this.numregle = numregle;
		this.libregle = libregle;
		this.scoremin = scoremin;
		this.mesActions = actions;
	}

	@Id
	@Column(name = "NUMREGLE", unique = true, nullable = false)
	public int getNumregle() {
		return this.numregle;
	}

	public void setNumregle(int numregle) {
		this.numregle = numregle;
	}

	@Column(name = "LIBREGLE", length = 25)
	public String getLibregle() {
		return this.libregle;
	}

	public void setLibregle(String libregle) {
		this.libregle = libregle;
	}

	@Column(name = "SCOREMIN")
	public Integer getScoremin() {
		return this.scoremin;
	}

	public void setScoremin(Integer scoremin) {
		this.scoremin = scoremin;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "regles")
	public List<Action>  getActions() {
		return this.mesActions;
	}

	public void setActions(List<Action>  actions) {
		this.mesActions = actions;
	}

}
